import { v4 as uuidv4 }          from 'uuid';
import jwt                        from 'jsonwebtoken';
import { getAuth }                from 'firebase-admin/auth';
import { getFirestore }           from 'firebase-admin/firestore';
import { createHttpError }        from '@shared/errors';
import { OutboxEventPublisher }   from '@shared/events';
import { logger }                 from '@shared/logger';
import { AppleAuthClient }        from '../../infrastructure/clients/AppleAuthClient';
import { config }                 from '../../config';

export interface AppleCallbackResult {
  firebaseToken: string;
  uid:           string;
  isNewUser:     boolean;
}

/**
 * Handles the Apple web OAuth callback (POST /auth/apple/callback).
 *
 * Flow:
 *  1. Verify `state` JWT to prevent CSRF (generated by GET /auth/apple/init)
 *  2. Exchange `code` at Apple's token endpoint → { id_token, refresh_token }
 *  3. Verify the returned `id_token` with Apple's JWKS
 *  4. Extract user info: email from id_token; name from `user` JSON (first sign-in only)
 *  5. Find or create Firebase Auth user + Firestore user doc
 *  6. Store Apple refresh_token on the user doc for future revocation
 *  7. Issue Firebase custom token → client calls signInWithCustomToken()
 */
export class AppleWebCallbackUseCase {
  constructor(
    private readonly appleClient: AppleAuthClient,
    private readonly outbox:      OutboxEventPublisher,
  ) {}

  async execute(
    code:        string,
    state:       string | undefined,
    userJson:    string | undefined,
    requestId:   string,
  ): Promise<AppleCallbackResult> {

    // 1 ── State verification (CSRF guard) ────────────────────────────────────
    //      State is a short-lived JWT signed by JWT_SECRET, issued by GET /auth/apple/init.
    //      Skip verification only if JWT_SECRET is not configured (emulator / local dev).
    if (config.jwtSecret && state) {
      try {
        jwt.verify(state, config.jwtSecret);
      } catch {
        throw createHttpError(400, 'INVALID_STATE', 'Apple OAuth state parameter is invalid or expired.');
      }
    } else if (config.jwtSecret && !state) {
      throw createHttpError(400, 'INVALID_STATE', 'Apple OAuth state parameter is required.');
    }

    // 2 ── Exchange authorization code for tokens ──────────────────────────────
    const tokens = await this.appleClient.exchangeCode(code);

    // 3 ── Verify the returned id_token ────────────────────────────────────────
    const payload = await this.appleClient.verifyIdToken(tokens.id_token);

    // 4 ── Extract user's display name (Apple only sends `user` on first sign-in) ──
    let firstName = payload.email.split('@')[0];
    let lastName  = '';
    if (userJson) {
      try {
        const parsed = JSON.parse(userJson) as {
          name?: { firstName?: string; lastName?: string };
        };
        if (parsed.name?.firstName) firstName = parsed.name.firstName;
        if (parsed.name?.lastName)  lastName  = parsed.name.lastName;
      } catch {
        logger.warn({ userJson }, 'Could not parse Apple user JSON');
      }
    }

    // 5 ── Find or create Firebase Auth user + Firestore doc ──────────────────
    let uid:       string;
    let isNewUser: boolean;
    // Tracked so we can embed them as developerClaims in the custom token,
    // guaranteeing the first ID token (from signInWithCustomToken) always has the
    // role claim — even before setCustomUserClaims propagates to Firebase's edge servers.
    let userRole:  string   = 'member';
    let userRoles: string[] = ['member'];

    try {
      const existingUser = await getAuth().getUserByEmail(payload.email);
      uid       = existingUser.uid;
      isNewUser = false;
    } catch {
      // User not found — create a new Member
      const newRecord = await getAuth().createUser({
        uid:           uuidv4(),
        email:         payload.email,
        displayName:   `${firstName} ${lastName}`.trim(),
        emailVerified: true,
      });
      uid       = newRecord.uid;
      isNewUser = true;

      await getAuth().setCustomUserClaims(uid, { role: 'member', roles: ['member'] });
      // userRole / userRoles keep their default 'member' values

      const now = new Date().toISOString();
      await getFirestore().collection('users').doc(uid).set({
        email:                   payload.email,
        firstName,
        lastName,
        role:                    'member',
        roles:                   ['member'],
        status:                  'approved',
        profilePhotoUrl:         null,
        preferredLanguage:       'en',
        fcmTokens:               [],
        notificationPreferences: { email: true, push: true },
        providers:               ['apple.com'],
        appleRefreshToken:       tokens.refresh_token,
        createdAt:               now,
        updatedAt:               now,
        deletedAt:               null,
      });

      await this.outbox.publishWithBatch({
        type:    'user.registered',
        payload: { uid, email: payload.email, firstName },
        requestId,
      });
    }

    // 6 ── For returning users: update provider list, refresh token, and claims ──
    if (!isNewUser) {
      const userDoc = await getFirestore().collection('users').doc(uid).get();
      if (userDoc.exists) {
        const data      = userDoc.data()!;
        const providers: string[] = (data['providers'] as string[] | undefined) ?? ['password'];
        await getFirestore().collection('users').doc(uid).update({
          ...(providers.includes('apple.com') ? {} : { providers: [...providers, 'apple.com'] }),
          appleRefreshToken: tokens.refresh_token,
          updatedAt:         new Date().toISOString(),
        });
        // Refresh Firebase Auth custom claims from Firestore source of truth so the
        // next ID token always reflects the user's current roles.
        userRoles = (data['roles'] as string[] | undefined) ?? ['member'];
        userRole  = (data['role']  as string  | undefined) ?? userRoles[0] ?? 'member';
        await getAuth().setCustomUserClaims(uid, { role: userRole, roles: userRoles });
      }
    }

    // 7 ── Issue Firebase custom token — embed role claims as developerClaims ───
    //      Guarantees the first ID token from signInWithCustomToken has the role
    //      claim, even before setCustomUserClaims propagates globally.
    const firebaseToken = await getAuth().createCustomToken(uid, { role: userRole, roles: userRoles });

    return { firebaseToken, uid, isNewUser };
  }
}
